version: "3.0"

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis

  wordpress:
    build: ./docker/wp
    environment:
      - VIRTUAL_HOST=content-sync-fusion.local
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=true
      - WORDPRESS_CONFIG_EXTRA=
          define('WP_DEBUG_LOG', true);
          define('WP_REDIS_HOST', 'redis');
          define('WP_CACHE_KEY_SALT', 'http://content-sync-fusion.local');
          define('DISABLE_WP_CRON', true);
          define('WP_LOCAL_DEV', true);
    depends_on:
      - db
      - redis
    volumes:
      - ./data/wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/content-sync-fusion
      - /var/www/html/wp-content/plugins/content-sync-fusion/vendor/
      - /var/www/html/wp-content/plugins/content-sync-fusion/node_modules/
      - ./docker/wp/htaccess:/var/www/html/.htaccess
      - ./docker/wp/csf_config.php:/var/www/html/wp-content/mu-plugins/csf_config.php

  db_test:
    image: mariadb
    ports:
      - 4406:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress_test
      - MYSQL_DATABASE=wordpress_test
      - MYSQL_USER=wordpress_test
      - MYSQL_PASSWORD=wordpress_test

  wordpress_test:
    build: ./docker/wp
    ports:
      - 8081:80
    environment:
      - WORDPRESS_DB_HOST=db_test
      - WORDPRESS_DB_USER=wordpress_test
      - WORDPRESS_DB_PASSWORD=wordpress_test
      - WORDPRESS_DB_NAME=wordpress_test
      - WORDPRESS_CONFIG_EXTRA=
          define('MULTISITE', true);
          define('SUBDOMAIN_INSTALL', false);
          define('DOMAIN_CURRENT_SITE', 'csf-test.local');
          define('PATH_CURRENT_SITE', '/');
          define('SITE_ID_CURRENT_SITE', 1);
          define('BLOG_ID_CURRENT_SITE', 1);
          define('WP_REDIS_HOST', 'redis');
          define('WP_CACHE_KEY_SALT', 'http://csf-test.local');
          define('DISABLE_WP_CRON', true);
          define('WP_LOCAL_DEV', true);
    depends_on:
      - db_test
    volumes:
      - .:/var/www/html/wp-content/plugins/content-sync-fusion
      - ./docker/wp/csf_config.php:/var/www/html/wp-content/mu-plugins/csf_config.php

  chromedriver:
    image: selenium/standalone-chrome:latest
    links:
      - wordpress_test:csf-test.local
    ports:
      - 4445:4444
volumes:
  db:
